django_project/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin


urlpatterns = patterns(
    '',

    # Enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # uncomment to enable defaut Django auth
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),

    # include application urls
    url(r'', include('flood_mapper.urls')),

)

# expose static files and uploded media if DEBUG is active
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': True
            }),
        url(r'', include('django.contrib.staticfiles.urls'))
    )

django_project/flood_mapper/urls.py
# coding=utf-8
"""URI Routing configuration for this apps."""
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(
        r'^add-flood-status-report/$',
        'flood_mapper.views.add_flood_status_report.add_flood_status_report'
    ),
    url(
        r'^flood_area_detail/$',
        'flood_mapper.views.flood_area_detail.flood_area_detail'
    ),
    url(
        r'^reports/$',
        'flood_mapper.views.reports.reports'
    ),
    url(
        r'^api/reports/rt/(?P<rt_id>[\d]+)/$',
        'flood_mapper.views.reports_api.reports_rt_api'
    ),
    url(
        r'^api/locations/(?P<village>[\d]+)'
        r'/(?P<rw>[\d]+)'
        r'/('r'?P<rt>[\d]+)/$',
        'flood_mapper.views.boundary_api.boundary_api'
    ),
    url(
        r'^api/locations/(?P<village>[\d]+)'
        r'/(?P<rw>[\d]+)/$',
        'flood_mapper.views.boundary_api.boundary_api'
    ),
    url(
        r'^api/locations/(?P<village>[\d]+)/$',
        'flood_mapper.views.boundary_api.boundary_api'
    ),
    url(
        r'^api/locations/$',
        'flood_mapper.views.boundary_api.boundary_api'
    ),
    url(
        r'^api/village/(?P<rw_id>[\d]+)/$',
        'flood_mapper.views.boundary_api.get_village_api'
    ),
)

django_project/flood_mapper/models/boundary.py
# coding=utf-8
"""Model class for WMS Resource"""
__author__ = 'christian'
__project_name = 'jakarta-flood-maps'
__filename = 'boundary.py'
__date__ = '24/11/2014'
__copyright__ = 'christian@kartoza.com'
__doc__ = ''

from django.core.validators import RegexValidator
from django.contrib.gis.db import models


class Boundary(models.Model):
    """Boundary is an abstract model that RT, RW and Village inherit from."""
    contact_person = models.CharField(max_length=100, blank=True, null=True)
    # from http://stackoverflow.com/a/19131360/1158060
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: "
                "'+6288888888888'. Up to 15 digits allowed.")
    contact_phone = models.CharField(
        max_length=15, validators=[phone_regex], blank=True, null=True)
    area = models.CharField(max_length=100, blank=True, null=True)

    population = models.IntegerField(blank=True, null=True)

    geometry = models.PolygonField(
        srid=4326, null=True, blank=True, help_text='The geographic boundary')

    id = models.AutoField(primary_key=True)

    objects = models.GeoManager()

    class Meta:
        abstract = True
        app_label = 'flood_mapper'

django_project/flood_mapper/models/flood_status.py
    # coding=utf-8
"""Model class for WMS Resource"""
__author__ = 'timlinux'
__project_name = 'jakarta-flood-maps'
__filename = 'village.py'
__date__ = '11/11/14'
__copyright__ = 'tim@kartoza.com'
__doc__ = ''

from django.contrib.gis.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from flood_mapper.models.rt import RT
from users.models import User

from rest_framework import serializers


class FloodStatus(models.Model):
    """Flood status model."""

    class Meta:
        """Meta class."""
        app_label = 'flood_mapper'

    name = models.CharField(max_length=200)
    rt = models.ForeignKey(
        RT,
        help_text='The RT that is affected.',
    )
    depth = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        help_text='The depth in metres that the RT is flooded.',
        validators=[
            MaxValueValidator(10),
            MinValueValidator(0)
        ]
    )
    date_time = models.DateTimeField()
    recorded_by = models.ForeignKey(User)
    reporter_name = models.CharField(
        max_length=100
    )
    reporting_medium = models.CharField(
        max_length=100
    )
    notes = models.TextField(
        blank=True,
        null=True
    )

    def __unicode__(self):
        return self.name

    def save_base(self, *args, **kwargs):
        self.name = '%s -- %s: %s' % (self.date_time, self.rt, self.depth)
        super(FloodStatus, self).save_base(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Overloaded save method."""
        super(FloodStatus, self).save(*args, **kwargs)


class FloodStatusSerializer(serializers.ModelSerializer):

    rw = serializers.SerializerMethodField('get_rw')
    village = serializers.SerializerMethodField('get_village')

    def get_rw(self, obj):
        return obj.rt.rw.id

    def get_village(self, obj):
        return obj.rt.rw.village.id

    class Meta:
        model = FloodStatus
        fields = ('id', 'date_time', 'rt', 'rw', 'village', 'depth')


class FloodStatusFullSerializer(FloodStatusSerializer):

    contact_person = serializers.SerializerMethodField('get_contact_person')
    contact_phone = serializers.SerializerMethodField('get_contact_phone')

    def get_contact_person(self, obj):
        return obj.rt.contact_person

    def get_contact_phone(self, obj):
        return obj.rt.contact_phone

    class Meta:
        model = FloodStatus
        fields = (
            'id', 'date_time', 'rt', 'rw', 'village', 'depth',
            'contact_person', 'contact_phone'
        )

django_project/flood_mapper/models/rt.py
    # coding=utf-8
"""Model class for villages."""
__author__ = 'timlinux'
__project_name = 'jakarta-flood-maps'
__filename = 'village.py'
__date__ = '11/11/14'
__copyright__ = 'tim@kartoza.com'
__doc__ = ''

import os
from django.contrib.gis.db import models
from django.conf.global_settings import MEDIA_ROOT
from django.utils.text import slugify
# from django.core.validators import MaxValueValidator, MinValueValidator
# from owslib.wms import WebMapService, ServiceException, CapabilitiesError

from flood_mapper.models.boundary import Boundary
from flood_mapper.models.rw import RW

from rest_framework import serializers


class RT(Boundary):
    """RW Boundary."""

    class Meta:
        """Meta class."""
        app_label = 'flood_mapper'

    slug = models.SlugField(max_length=100)

    name = models.CharField(
        help_text='A name for the RT.',
        null=False,
        blank=False,
        unique=False,
        max_length=100
    )

    rw = models.ForeignKey(RW)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Overloaded save method."""
        self.slug = slugify(unicode(self.name))
        super(RT, self).save(*args, **kwargs)


class RTSerializer(serializers.ModelSerializer):

    class Meta:
        model = RT
        fields = ('id', 'name', 'slug', 'population', 'geometry')

django_project/flood_mapper/models/rw.py
    # coding=utf-8
"""Model class for villages."""
__author__ = 'timlinux'
__project_name = 'jakarta-flood-maps'
__filename = 'village.py'
__date__ = '11/11/14'
__copyright__ = 'tim@kartoza.com'
__doc__ = ''

import os
from django.contrib.gis.db import models
from django.conf.global_settings import MEDIA_ROOT
from django.utils.text import slugify
# from django.core.validators import MaxValueValidator, MinValueValidator
# from owslib.wms import WebMapService, ServiceException, CapabilitiesError

from flood_mapper.models.boundary import Boundary
from flood_mapper.models.village import Village

from rest_framework import serializers


class RW(Boundary):
    """RW Boundary."""

    class Meta:
        """Meta class."""
        app_label = 'flood_mapper'

    slug = models.SlugField(max_length=100)

    name = models.CharField(
        help_text='A name for the RW.',
        null=False,
        blank=False,
        unique=False,
        max_length=100
    )

    village = models.ForeignKey(Village)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Overloaded save method."""
        self.slug = slugify(unicode(self.name))
        super(RW, self).save(*args, **kwargs)


class RWSerializer(serializers.ModelSerializer):

    def transform_geometry(self, obj, value):
        if obj.geometry:
            return obj.geometry.json
        else:
            return ''

    class Meta:
        model = RW
        fields = ('id', 'name', 'slug', 'population', 'geometry')

django_project/flood_mapper/models/village.py
    # coding=utf-8
"""Model class for villages."""
__author__ = 'timlinux'
__project_name = 'jakarta-flood-maps'
__filename = 'village.py'
__date__ = '11/11/14'
__copyright__ = 'tim@kartoza.com'
__doc__ = ''

import os
from django.contrib.gis.db import models
from django.conf.global_settings import MEDIA_ROOT
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator

from flood_mapper.models.boundary import Boundary

from rest_framework import serializers


class Village(Boundary):
    """Village model.

    Note: We should make a boundary base class or decorator and then
    let village, RW and RT inherit from it since they have many fields in
    common.
    """

    class Meta:
        """Meta class."""
        app_label = 'flood_mapper'

    slug = models.SlugField(
        max_length=100,
        unique=True
    )

    name = models.CharField(
        help_text='A name for the village.',
        null=False,
        blank=False,
        unique=True,
        max_length=100
    )

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Overloaded save method."""
        self.slug = slugify(unicode(self.name))
        super(Village, self).save(*args, **kwargs)


class VillageSerializer(serializers.ModelSerializer):

    class Meta:
        model = Village
        fields = ('id', 'name', 'slug', 'population', 'geometry')

django_project/flood_mapper/forms/add_flood_status_report.py
from flood_mapper.models.flood_status import FloodStatus

from django.conf import settings
from django import forms

from flood_mapper.models.village import Village
from flood_mapper.models.rw import RW
from flood_mapper.models.rt import RT

import decimal


class AddFlodStatusForm(forms.ModelForm):
    village = forms.ChoiceField(
        required=False,
        help_text="The village of the affected RT."
    )
    rw = forms.ChoiceField(
        required=False,
        help_text="The RW of the affected RT.",
        choices=[
            (rw_choice.id, rw_choice.name) for rw_choice in RW.objects.all()
        ]
    )

    def __init__(self, *args, **kwargs):
        super(AddFlodStatusForm, self).__init__(*args, **kwargs)
        self.fields['rt'].widget.choices = [('', '---------')]
        self.fields['rw'].widget.choices = [('', '---------')]
        print self.fields['rw'].validators
        # TODO: only show the villages, that this user is allowed to sees
        self.fields['village'].choices = [('', '---------')] + [
            (village.id, village.name) for village in Village.objects.all()]

    def clean(self):
        cleaned_data = self.cleaned_data
        depth = cleaned_data.get('depth')
        if depth is not None:
            cleaned_data['depth'] = decimal.Decimal(depth)
        print cleaned_data
        print self.errors
        return cleaned_data

    class Meta:
        fields = ['village', 'rw', 'rt', 'depth', 'date_time', 'notes']
        model = FloodStatus

django_project/flood_mapper/views/add_flood_status_report.py
# coding=utf-8
"""Views."""
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from users.models import User

# from flood_mapper.models.flood_status import FloodStatus
# from flood_mapper.app_settings import *

from flood_mapper.forms.add_flood_status_report import AddFlodStatusForm


# @login_required
# @staff_member_required
def add_flood_status_report(request):
    """Add a flood status report

    :param request: A django request object.
    :type request: request

    :returns: Returns a flood status rport
    :rtype: HttpResponse
    """
    if request.method == "POST":
        form = AddFlodStatusForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            # model_instance.recorded_by = request.user
            model_instance.recorded_by = User.objects.all()[0]
            model_instance.save()
            return redirect('/')
        else:
            return render(
                request,
                'flood_mapper/add_flood_status_report.html',
                context_instance=RequestContext(request, {'form': form}))

    form = AddFlodStatusForm()

    return render(
        request,
        'flood_mapper/add_flood_status_report.html',
        context_instance=RequestContext(request, {'form': form}))

django_project/flood_mapper/views/boundary_api.py
from flood_mapper.models.rw import RW, RWSerializer
from flood_mapper.models.rt import RT, RTSerializer
from flood_mapper.models.village import Village, VillageSerializer
from rest_framework.response import Response

from rest_framework.decorators import api_view

@api_view(['GET'])
def boundary_api(request, village=None, rw=None, rt=None):
    """
    API endpoint that allows users to be viewed or edited.
    """
    if rt:
        try:
            print type(rt), rw, village
            matching_rt = RT.objects.get(
                id=int(rt),
                rw__id=int(rw),
                rw__village__id=int(village))
            return Response(RTSerializer(matching_rt).data)
        except RT.DoesNotExist:
            return Response(None)
    elif rw:
        if not village:
            return Response(None)
        matching_rts = RT.objects.filter(
            rw__id=int(rw),
            rw__village__id=int(village))
        return Response(RTSerializer(matching_rts, many=True).data)
    elif village:
        matching_rts = RW.objects.filter(
            village__id=int(village))
        return Response(RWSerializer(matching_rts, many=True).data)
    else:
        return Response(
            VillageSerializer(Village.objects.all(), many=True).data)


@api_view(['GET'])
def get_village_api(request, rw_id):
    try:
        rw = RW.objects.get(id=int(rw_id))
        village = rw.village
        return Response(VillageSerializer(village).data)
    except RW.DoesNotExist:
        return Response(None)

django_project/flood_mapper/views/flood_area_detail.py
# coding=utf-8
"""Views."""
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext



# @login_required
# @staff_member_required
def flood_area_detail(request):

    return render(
        request,
        # 'flood_mapper/add_flood_status_report.html',
        'flood_mapper/flood_area_detail.html',
        context_instance=RequestContext(request, {}))

django_project/flood_mapper/views/reports.py
# coding=utf-8
"""Views."""
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext



# @login_required
# @staff_member_required
def reports(request):

    return render(
        request,
        'flood_mapper/reports.html',
        context_instance=RequestContext(request, {}))

django_project/flood_mapper/views/reports_api.py
from flood_mapper.models.rw import RW, RWSerializer
from flood_mapper.models.flood_status import (
    FloodStatus,
    FloodStatusSerializer,
    FloodStatusFullSerializer
)
from flood_mapper.models.rt import RT, RTSerializer
from flood_mapper.models.village import Village, VillageSerializer
from rest_framework.response import Response

from rest_framework.decorators import api_view

@api_view(['GET'])
def reports_rt_api(request, rt_id):
    """
    Get a report associated with a rw
    """
    flood_status_reports = FloodStatus.objects.filter(rt__id=int(rt_id))

    if 1:  # TODO: Logged in user
        return Response(
            FloodStatusSerializer(flood_status_reports, many=True).data)
    else:
        return Response(
            FloodStatusFullSerializer(flood_status_reports, many=True).data)

django_project/flood_mapper/templates/flood_mapper/add_flood_status_report.html
{% extends "flood_mapper/base.html" %}
{% block header %}
  <script src="/static/js/moment.min.js"></script>
  <script src="/static/js/bootstrap-datetimepicker.min.js"></script>
  <link rel="stylesheet" href="/static/css/bootstrap-datetimepicker.min.css" />
  <script>
    function update_rws(){
      var village_id = $('#id_village').val();
      var rw_select = $('#id_rw');
      var rt_select = $('#id_rt');
      rw_select.find('option').remove().end();
      rw_select.append($("<option></option>")
        .attr("value", '')
        .text('---------'));
      rt_select.find('option').remove().end();
      rt_select.append($("<option></option>")
        .attr("value", '')
        .text('---------'));
      if (village_id == ''){
        return;
      }
      $.get('/api/locale/' + village_id + '/?format=json', function(data){
        $.each(data, function(dummy, rw){
          $('#id_rw').append($("<option></option>")
           .attr("value", rw['id'])
           .text(rw['name']));
        });
      });
    }
    function update_rts(){
      var village_id = $('#id_village').val();
      var rw_id = $('#id_rw').val();
      var rt_select = $('#id_rt');
      rt_select.find('option').remove().end();
      rt_select.append($("<option></option>")
        .attr("value", '')
        .text('---------'));
      if ((village_id == '') || (rw_id == '')){
        console.log('returning');
        return;
      }
      $.get('/api/locale/' + village_id + '/' + rw_id + '/?format=json', function(data){
        $.each(data, function(dummy, rt){
          $('#id_rt').append($("<option></option>")
           .attr("value", rt['id'])
           .text(rt['name']));
        });
      });
    }
    $(document).ready(function(){
      // Setup locale selecton
      $('#id_village').on('change', update_rws);
      $('#id_rw').on('change', update_rts);
      // Setup date time picker
      var date_time = $('#id_date_time');
      date_time.datetimepicker(
      {
        format: 'YYYY-MM-DD HH:mm'
      });
    });
  </script>
  <title>Add flood status report</title>
{%  endblock %}

{% load bootstrap_tags %}

{% block navigation-bar %}
  {% include "flood_mapper/navigation_bar.html" %}
{%  endblock %}

{% block content %}
<div>
  <form action="/add-flood-status-report/" method="post">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <button type="submit" class="btn btn-block btn-primary">Add</button>
  </form>
</div>

</div> <!-- /container -->
{%  endblock %}

django_project/flood_mapper/templates/flood_mapper/base.html
<!DOCTYPE html>
<html>
<head lang="en">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css" />
  <link rel="stylesheet" href="/static/css/leaflet.css" />
  <script src="/static/js/jquery-1.11.1.min.js"></script>
  <script src="/static/js/leaflet.js"></script>
  <script src="/static/js/bootstrap.js"></script>
  <meta charset="UTF-8">
  <script>
    var map;

    function show_side_panel(){
      var map_div = $('#map');
      var side_panel = $('#side_panel');
      map_div.addClass('col-xs-8');
      side_panel.addClass('col-xs-4');
      side_panel.show();
      map_div.removeClass('col-xs-12');
      map.invalidateSize();
    }

    function hide_side_panel(){
      var map_div = $('#map');
      var side_panel = $('#side_panel');
      map_div.addClass('col-xs-12');
      side_panel.removeClass('col-xs-4');
      side_panel.hide();
      map_div.removeClass('col-xs-8');
      map.invalidateSize();
    }

    $(document).ready(function() {
      $('#navigationbar').css('height', window.innerHeight * 0.1);
      $('#map').css('height', window.innerHeight * 0.9);
      map = L.map('map').setView([-6.2000, 106.8167], 11);
      L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

    });
  </script>
  {% block header %}
    <title></title>
  {% endblock %}
</head>
<body>

<div id="navigation_bar">
  {% block navigation-bar %}
  {% endblock %}
</div>
<div class="row">
  <div class="col-xs-8" id="map">
  </div>
  <div class="col-xs-4" id="side_panel">
    {% block content %}
    {%  endblock %}
  </div>
</div>
</body>
</html>

django_project/flood_mapper/templates/flood_mapper/flood_area_detail.html
{% extends "flood_mapper/base.html" %}
{% block header %}
  <script>
    function add_rw_to_map(){
      $.get('/api/locations/?format=json', function(data){
        $.each(data, function(dummy, village){
          $.get('/api/locations/' + village['id'] + '/?format=json', function(data){
            $.each(data, function(dummy, rw){
              var rw_layer = JSON.parse(rw['geometry']);
              L.geoJson(rw_layer, {
                style: style,
                onEachFeature: onEachFeature,
                properties: {
                  rw_id: rw['id'],
                  name: rw['name'],
                  population: rw['population']
                }
              }).addTo(map);
            });
          });
        });
      });
    }

    function updateFloodAreaReport(){
      var rt = $('#rt');
      rt.prop('disabled', 'disabled');
      var rt_id = rt.val();
      $.get('/api/reports/rt/' + rt_id + '/?format=json', function(data){
        console.log(data);
        if (data.length == 0){
          console.log('No reported flood info');
        } else {
          $('#current_flood_depth').text(data[0]["depth"]);
          $('#current_flood_depth_div').show();
        }
        rt.prop('disabled', false);
      })
    }

    function updateFloodAreaOptions(rw_id, rw_name){
      $('#rw').text(rw_name);
      $('#village').text('');
      var rt_select = $('#rt');
      rt_select.find('option').remove().end();
      rt_select.append($("<option></option>")
        .attr("value", '')
        .text('---------'));
      $.get('/api/village/' + rw_id + '/?format=json', function(data){
        $('#village').text(data['name']);
        var village_id = data['id'];
        $.get('/api/locations/' + village_id + '/' +rw_id + '/?format=json', function(data) {
           $.each(data, function(dummy, rt) {
             rt_select.append($("<option></option>")
               .attr("value", rt['id'])
               .text(rt['name']));
           });
        });
      });
    }

    function style(feature) {
      return {
        weight: 2,
        opacity: 1,
        color: 'blue',
        dashArray: '3',
        fillOpacity: 0.5,
        fillColor: 'blue'
      };
    }

    function highlightFeature(e) {
      var layer = e.target;
      layer.setStyle({
        weight: 5,
        color: 'white',
        dashArray: '',
        fillOpacity: 0.3,
        fillColor: 'blue'
      });
      if (!L.Browser.ie && !L.Browser.opera) {
        layer.bringToFront();
      }
    }

    function resetHighlight(e) {
      var layer = e.target;
      layer.setStyle(style(e));
    }

    function zoomToFeature(e) {
      var layer = e.target;
      map.fitBounds(layer.getBounds());
      $('#select_rw').hide();
      $('#staff_details').hide();
      $('#current_flood_depth_div').hide();
      $('#details').show();

      var rw_id = layer["options"]["properties"]["rw_id"];
      var rw_name = layer["options"]["properties"]["name"];
      updateFloodAreaOptions(rw_id, rw_name);
    }

    function onEachFeature(feature, layer) {
      layer.on({
        mouseover: highlightFeature,
        mouseout: resetHighlight,
        click: zoomToFeature
      });
    }

    $(document).ready(function(){
      // add rw's to map
      add_rw_to_map();
      $('#rt').on('change', updateFloodAreaReport);
    });

  </script>
  <title>Flood area details</title>
{%  endblock %}

{% load bootstrap_tags %}

{% block navigation-bar %}
  {% include "flood_mapper/navigation_bar.html" %}
{%  endblock %}

{% block content %}
<div>
  <h1>Flood Area Detail</h1>
  <div id="select_rw">
    <h2>Select a RW</h2>
  </div>
  <div id="details" style="display: None">
    <div class="row">
      <div class="col-xs-4">Village:</div>
      <div class="col-xs-8" id="village"></div>
    </div>
    <div class="row">
      <div class="col-xs-4">RW:</div>
      <div class="col-xs-8" id="rw"></div>
    </div>
    <div class="row">
      <div class="col-xs-4">RT:</div>
      <select class="col-xs-8" id="rt">
        <option value="">---------</option>
      </select>
    </div>
    <div class="row" id="current_flood_depth_div">
      <div class="col-xs-4">Current flood depth:</div>
      <div class="col-xs-8" id="current_flood_depth"></div>
    </div>
    <div id="staff_details">
      <div class="row">
        <h2> Details visible to staff only</h2>
      </div>
      <div class="row">
        <div class="col-xs-4">Contact person:</div>
        <div class="col-xs-8" id="contact_person"></div>
      </div>
      <div class="row">
        <div class="col-xs-4">Contact number:</div>
        <div class="col-xs-8" id="contact_number"></div>
      </div>
    </div>
  </div>
</div> <!-- /container -->
{%  endblock %}

django_project/flood_mapper/templates/flood_mapper/navigation_bar.html
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Jakarta Flood Maps</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Login</a></li>
      </ul>
    </div>
  </div>
</nav>